version: '3.8'

services:
  # Python 3.8 base image
  python38-base:
    build:
      context: .
      dockerfile: python38.Dockerfile
    image: vqa-system/python38-base:latest
    container_name: vqa-python38-base
    command: python --version

  # Python 3.9 base image  
  python39-base:
    build:
      context: .
      dockerfile: python39.Dockerfile
    image: vqa-system/python39-base:latest
    container_name: vqa-python39-base
    command: python --version

  # CUDA 12 base image
  cuda12-base:
    build:
      context: .
      dockerfile: cuda12.Dockerfile
    image: vqa-system/cuda12-base:latest
    container_name: vqa-cuda12-base
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    command: python -c "import torch; print(f'CUDA available: {torch.cuda.is_available()}')"

  # MATLAB Runtime base image
  matlab-base:
    build:
      context: .
      dockerfile: matlab.Dockerfile
    image: vqa-system/matlab-base:latest
    container_name: vqa-matlab-base
    command: echo "MATLAB Runtime ready"

# Networks
networks:
  default:
    name: vqa-network
    driver: bridge